import { Jacquarda_Bastarda_9 } from "next/font/google";
import "./globals.css";
const jacq = Jacquarda_Bastarda_9({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Gallery Storage App",
  description: "Generated by create next app",
  icons: {
    icon: "/image.png", // Default icon (can be png, svg, etc.)
    shortcut: "/shortcut-icon.png", // Shortcut icon (for pinned tabs, etc.)
    apple: "/apple-touch-icon.png", // Apple touch icon for iOS devices
    other: [
      {
        rel: "icon",
        type: "image/png",
        sizes: "192x192",
        url: "/icon-192x192.png",
      }, // Custom resolution icon
      {
        rel: "icon",
        type: "image/png",
        sizes: "512x512",
        url: "/icon-512x512.png",
      }, // Larger icon for Android
    ],
  },
  // openGraph: {
  //   title: "My App",
  //   description: "A Next.js 14 App showcasing an image in metadata",
  //   url: "https://myapp.com",
  //   images: [
  //     {
  //       url: "/image.png",
  //       width: 1200,
  //       height: 630,
  //       alt: "My App Logo",
  //     },
  //   ],
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jacq.className}>{children}</body>
    </html>
  );
}
