import {Roboto_Mono} from "next/font/google"
import "./globals.css";

const mono=Roboto_Mono({subsets:["latin"],weight:"500"})
export const metadata = {
  title: "Gallery Storage App",
  description: "Generated by create next app",
  icons: {
    icon: "/image.png", // Default icon (can be png, svg, etc.)
    shortcut: "/shortcut-icon.png", // Shortcut icon (for pinned tabs, etc.)
    apple: "/apple-touch-icon.png", // Apple touch icon for iOS devices
  
  },
 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mono.className}>{children}</body>
    </html>
  );
}
